In [1]:
import numpy as np

In [2]:
# Creating numpy /n-d Array

In [3]:
import array

In [4]:
arr1=array.array('i',[1,2,3,4,5])
arr1

array('i', [1, 2, 3, 4, 5])

In [5]:
type(arr1)

array.array

In [6]:
from array import*
arr2=array('i',[1,2,3,4,5,6])
arr2

array('i', [1, 2, 3, 4, 5, 6])

In [7]:
type(arr2)

array.array

In [8]:
arr3=np.array([1,2,3,4,5,6,7])
arr3

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
type(arr3)

numpy.ndarray

In [10]:
arr4=np.array([[1,2,3,4],[2,3,4,5]])
arr4

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [11]:
type(arr4)

numpy.ndarray

In [12]:
arr5=np.zeros((3,3),dtype='int')
arr5

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [13]:
arr6=np.ones((2,3),dtype='int')
arr6

array([[1, 1, 1],
       [1, 1, 1]])

In [14]:
arr7=np.identity(5,dtype='int')
arr7

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [15]:
arr8=np.arange(10)   # here range is numpy
arr8

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr9=np.linspace(10,20,num=20) ## here 10 to 20,15 values
arr9

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

In [20]:
np.exp(arr9)

array([2.20264658e+04, 3.72838595e+04, 6.31098147e+04, 1.06825012e+05,
       1.80821052e+05, 3.06073010e+05, 5.18085071e+05, 8.76954621e+05,
       1.48440758e+06, 2.51263385e+06, 4.25309663e+06, 7.19915117e+06,
       1.21858923e+07, 2.06268723e+07, 3.49147891e+07, 5.90997258e+07,
       1.00037196e+08, 1.69331421e+08, 2.86624688e+08, 4.85165195e+08])

In [21]:
arr01=arr9.copy()

In [22]:
arr01

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

In [23]:
arr5.shape

(3, 3)

In [24]:
arr10=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr10

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [25]:
arr10.shape

(2, 2, 2)

In [26]:
arr10.ndim

3

In [27]:
arr10.size

8

In [28]:
arr10.itemsize

4

In [29]:
arr10.item

<function ndarray.item>

In [30]:
arr10.dtype

dtype('int32')

In [31]:
arr10.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [32]:
arr10.astype('int')

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [33]:
lista=range(100)
arr11=np.arange(100)

In [34]:
lista

range(0, 100)

In [35]:
import sys

In [36]:
arr11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [37]:
print(sys.getsizeof(87)*len(lista))

2800


In [38]:
print(arr11.itemsize*arr11.size)

400


In [39]:
import time
import datetime

In [40]:
x=range(10000)
y=range(10000,20000)

In [41]:
start_time=time.time()

In [42]:
c=[(x+y) for x,y in zip(x,y)]
c

[10000,
 10002,
 10004,
 10006,
 10008,
 10010,
 10012,
 10014,
 10016,
 10018,
 10020,
 10022,
 10024,
 10026,
 10028,
 10030,
 10032,
 10034,
 10036,
 10038,
 10040,
 10042,
 10044,
 10046,
 10048,
 10050,
 10052,
 10054,
 10056,
 10058,
 10060,
 10062,
 10064,
 10066,
 10068,
 10070,
 10072,
 10074,
 10076,
 10078,
 10080,
 10082,
 10084,
 10086,
 10088,
 10090,
 10092,
 10094,
 10096,
 10098,
 10100,
 10102,
 10104,
 10106,
 10108,
 10110,
 10112,
 10114,
 10116,
 10118,
 10120,
 10122,
 10124,
 10126,
 10128,
 10130,
 10132,
 10134,
 10136,
 10138,
 10140,
 10142,
 10144,
 10146,
 10148,
 10150,
 10152,
 10154,
 10156,
 10158,
 10160,
 10162,
 10164,
 10166,
 10168,
 10170,
 10172,
 10174,
 10176,
 10178,
 10180,
 10182,
 10184,
 10186,
 10188,
 10190,
 10192,
 10194,
 10196,
 10198,
 10200,
 10202,
 10204,
 10206,
 10208,
 10210,
 10212,
 10214,
 10216,
 10218,
 10220,
 10222,
 10224,
 10226,
 10228,
 10230,
 10232,
 10234,
 10236,
 10238,
 10240,
 10242,
 10244,
 10246,
 10248,


In [43]:
print(time.time()-start_time)

0.7680439949035645


In [44]:
a=np.arange(100000)
b=np.arange(100000,200000)

In [45]:
start_time=time.time()
c=a+b

print(time.time()-start_time)

0.0010263919830322266


In [46]:
arr12=np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [47]:
arr12[2]

array([ 8,  9, 10, 11])

In [48]:
arr12[-1]

array([20, 21, 22, 23])

In [49]:
arr12[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [50]:
arr12[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [51]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [52]:
arr12[4:6,2:4]

array([[18, 19],
       [22, 23]])

In [53]:
# iteration
for i in np.nditer(arr12):
    print(i,end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 

In [54]:
#numpy operations
arrr1=np.array([1,2,3,4,5,6])
arrr2=np.array([4,5,6,7,8,9])

In [55]:
arrr1-arrr2

array([-3, -3, -3, -3, -3, -3])

In [56]:
arrr1*arrr2

array([ 4, 10, 18, 28, 40, 54])

In [57]:
arrr1/arrr2

array([0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
       0.66666667])

In [58]:
arrr1+arrr2

array([ 5,  7,  9, 11, 13, 15])

In [59]:
arrr1*10

array([10, 20, 30, 40, 50, 60])

In [60]:
arrr2*10

array([40, 50, 60, 70, 80, 90])

In [61]:
np.sin(arrr1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ])

In [62]:
np.median(arrr1)

3.5

In [64]:
np.cos(arrr1)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029])

In [68]:
np.tan(arrr1)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619])

In [69]:
arrr1.std()

1.707825127659933

In [62]:
np.exp(arrr1)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 , 403.42879349])

In [63]:
np.sqrt(arrr1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

# Reshaping Numpy Array
1.Ravel
2.Reshape
3. Transpose
4.Stacking
5.Splitting

In [64]:
arrr1

array([1, 2, 3, 4, 5, 6])

In [65]:
arrr1.ravel()

array([1, 2, 3, 4, 5, 6])

In [66]:
arrr2.transpose()

array([4, 5, 6, 7, 8, 9])

In [67]:
np.transpose(arrr2)

array([4, 5, 6, 7, 8, 9])

In [68]:
arrr3=np.arange(12,18).reshape(2,3)

In [69]:
arrr3

array([[12, 13, 14],
       [15, 16, 17]])

In [70]:
import numpy as np

In [71]:
arrr4=np.arange(24).reshape(3,4,2)

In [72]:
arrr4

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [73]:
arrr5=arrr4.reshape(4,2,3)
arrr5

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [74]:
arrr5.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [75]:
arrr4.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

# Indexing with Boolean Arrays

In [76]:
import numpy as np

In [77]:
arr=np.random.randint(low=1,high=5,size=20).reshape(4,5)
arr

array([[3, 3, 4, 1, 2],
       [1, 1, 3, 3, 4],
       [4, 4, 4, 3, 3],
       [4, 4, 2, 3, 3]])

In [78]:
np.random.randint(low=0,high=10,size=25).reshape(5,5)>5

array([[False, False,  True, False, False],
       [ True, False, False, False,  True],
       [False, False,  True,  True, False],
       [False, False, False,  True,  True],
       [False,  True, False,  True, False]])

In [79]:
arr>50

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [80]:
arr[(arr>50) & (arr%2!=0)]=0

In [81]:
arr

array([[3, 3, 4, 1, 2],
       [1, 1, 3, 3, 4],
       [4, 4, 4, 3, 3],
       [4, 4, 2, 3, 3]])

In [82]:
x=np.linspace(-40,40,10)
x

array([-40.        , -31.11111111, -22.22222222, -13.33333333,
        -4.44444444,   4.44444444,  13.33333333,  22.22222222,
        31.11111111,  40.        ])

In [83]:
x.size

10

In [84]:
y=np.sin(x)

In [85]:
y.size

10

In [86]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
plt.plot(x,y)

In [ ]:
y=x*x+2*x+6

In [ ]:
plt.plot(x,y)

In [ ]:
a=np.random.rand(4,3)   # random function is output is the uniform distribution range(0-1),avgg,mean anything
a

In [ ]:
b=np.random.randn(2,3,3) # std normal distribution mean =0 and standard deviation=1
b

In [92]:
c=np.random.randint(3,3)
c

ValueError: low >= high

In [101]:
x=np.mat(np.random.randn(2,2))
x

matrix([[-1.34756687,  1.52067745],
        [ 0.61008921, -0.31907141]])

In [102]:
y=np.mat(np.random.randn(2,2))
y

matrix([[-0.33709182, -1.14069636],
        [-2.2266307 ,  0.41955647]])

In [105]:
z=x+y
z

matrix([[-0.67418365, -2.28139272],
        [-4.45326141,  0.83911295]])

In [107]:
a=x-y
a

matrix([[0., 0.],
        [0., 0.]])

In [108]:
q=x*y
q

matrix([[ 2.65354044, -0.09406713],
        [-0.18361832,  2.71593718]])