In [1]:
import numpy as np
import pandas as pd
from numpy.random import randint as rn
a=np.random.random((3,3))
a=np.round(a*0.5)
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [2]:
a=[0.6,0.8,1.2,1.5,1.8,1.3,0.5,-0.8]
[round(x) for x in a]

[1, 1, 1, 2, 2, 1, 0, -1]

In [3]:
df=pd.DataFrame(np.random.randn(4,5),index=list('asdf'),columns=list('qwert'))
df

q         w         e         r         t
a  0.471992 -1.459733  0.563323 -0.375469  0.588493
s  0.223409 -0.712256  0.329362 -0.660914  0.432659
d  0.721965 -0.987086  0.945527  0.334316 -1.963223
f  0.493293 -0.836919  0.340636  0.663581 -0.944759

In [7]:
df['h']=[1,2,1,2]
df

q         w         e         r         t  h
a  0.471992 -1.459733  0.563323 -0.375469  0.588493  1
s  0.223409 -0.712256  0.329362 -0.660914  0.432659  2
d  0.721965 -0.987086  0.945527  0.334316 -1.963223  1
f  0.493293 -0.836919  0.340636  0.663581 -0.944759  2

In [10]:
df.groupby('h')

In [11]:
df['q'].transform(round(i) for i in df['q'])

TypeError: Transform function failed

# boolean Indexing

In [12]:
a=np.random.randint(1,100,24).reshape(6,4)
a

array([[62, 92, 44, 55],
       [25, 51, 16, 64],
       [50, 11, 41, 27],
       [69, 67, 11, 98],
       [28, 62, 30,  9],
       [71, 72, 18, 39]])

In [13]:
a>50  # boolean array, find all the numbers greater then 50

array([[ True,  True, False,  True],
       [False,  True, False,  True],
       [False, False, False, False],
       [ True,  True, False,  True],
       [False,  True, False, False],
       [ True,  True, False, False]])

In [14]:
a[a>50] # filter  the data

array([62, 92, 55, 51, 64, 69, 67, 98, 62, 71, 72])

In [15]:
a%2==0 # find the even numbers

array([[ True,  True,  True, False],
       [False, False,  True,  True],
       [ True, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True, False],
       [False,  True,  True, False]])

In [16]:
a[a%2==0]

array([62, 92, 44, 16, 64, 50, 98, 28, 62, 30, 72, 18])

In [17]:
(a>50)&(a%2==0) # find the even numbers greater then 50

array([[ True,  True, False, False],
       [False, False, False,  True],
       [False, False, False, False],
       [False, False, False,  True],
       [False,  True, False, False],
       [False,  True, False, False]])

In [18]:
a[(a>50)&(a%2==0)]

array([62, 92, 64, 98, 62, 72])

In [19]:
a[a%7==0]

array([98, 28])

# Broadcasting
> The terms broadcasting describe How NumPy treats arrays with different shapes during airthmatics operations 

In [20]:
# same shape
a=np.arange(6).reshape(2,3)
b=np.arange(6,12).reshape(2,3)
print(a)
print()
print(b)

[[0 1 2]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]


In [21]:
b.shape[0]

2

In [22]:
np.append(b,np.random.random(b.shape[0],1),axis=1)

TypeError: random() takes at most 1 positional argument (2 given)

In [23]:
np.concatenate((a,b),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# np.where ()
> The numpy.where() functions returns the indices of elements in a input array where 

In [24]:
c=np.random.randint(1,100,24).reshape(6,4)
c

array([[ 5,  8, 26, 63],
       [ 7, 48, 30, 76],
       [75, 60, 90, 30],
       [16, 21, 27, 69],
       [87, 42, 63, 10],
       [51, 44, 63, 87]])

In [25]:
np.where(c>50,0,c) # more then 50 is 0 and less then as it 

array([[ 5,  8, 26,  0],
       [ 7, 48, 30,  0],
       [ 0,  0,  0, 30],
       [16, 21, 27,  0],
       [ 0, 42,  0, 10],
       [ 0, 44,  0,  0]])

In [26]:
np.where(c%2==0,0,c) # even

array([[ 5,  0,  0, 63],
       [ 7,  0,  0,  0],
       [75,  0,  0,  0],
       [ 0, 21, 27, 69],
       [87,  0, 63,  0],
       [51,  0, 63, 87]])

# np.argmax()
> The numpy.argmax() function returns indices of the max element of the array in perticular axis.

In [27]:
np.argmax(c)

10

# np.cumsum()
> numpy.cumsum()  function is used when we want to compute the cumulative sum of array elements over a given axis.

In [28]:
np.cumsum(c)

array([   5,   13,   39,  102,  109,  157,  187,  263,  338,  398,  488,
        518,  534,  555,  582,  651,  738,  780,  843,  853,  904,  948,
       1011, 1098])

In [29]:
np.cumprod(c)

array([          5,          40,        1040,       65520,      458640,
          22014720,   660441600, -1346045952,  2125768704, -1302896640,
       -1296580608,  -242712576,   411566080,    52953088,  1429733376,
        -132644864,  1344798720,   646971392,  2104492032,  -429916160,
        -450887680,  1635778560,   -25165824,  2105540608])

In [30]:
np.percentile(c,70) # 70 percent of the datasets

63.0

# np.histogram()
> Numpy has a build in numpy.histogram() functions which represents the frequency of the data distributions in the graphical form.
> bins size are also are important because bins are also represent range.

In [31]:
np.histogram(c,bins=[10,20,30,40,50,60,70])

(array([2, 3, 2, 3, 1, 5], dtype=int64), array([10, 20, 30, 40, 50, 60, 70]))

In [32]:
# correlation
np.corrcoef(c)

array([[ 1.        ,  0.80694731, -0.69172322,  0.98213668, -0.80826849,
         0.97923705],
       [ 0.80694731,  1.        , -0.83870665,  0.8585095 , -0.99971385,
         0.67239344],
       [-0.69172322, -0.83870665,  1.        , -0.81479698,  0.85146735,
        -0.60235683],
       [ 0.98213668,  0.8585095 , -0.81479698,  1.        , -0.86315162,
         0.94495555],
       [-0.80826849, -0.99971385,  0.85146735, -0.86315162,  1.        ,
        -0.67500602],
       [ 0.97923705,  0.67239344, -0.60235683,  0.94495555, -0.67500602,
         1.        ]])

In [33]:
salary=np.array([20,50,40,80,90,700,60,500,70,])
experience=np.array([1,2,3,4,5,6,7,8,9])

In [28]:
np.corrcoef(salary,experience)

array([[1.        , 0.41202861],
       [0.41202861, 1.        ]])

In [29]:
c[np.isin(c,salary)]

array([40, 80])

In [30]:
np.put(salary,[0,1],[5300,8000]) # update the elements with the hepl of index

In [31]:
salary

array([5300, 8000,   40,   80,   90,  700,   60,  500,   70])

In [32]:
np.delete(salary,0)  # delete the elements with the help of index

array([8000,   40,   80,   90,  700,   60,  500,   70])

In [33]:
import numpy as np

In [34]:
s=[1,2,3,4,5,6,7,8,9,8,7,6,5,4,3,2,1]

In [35]:
np.mean(s)

4.764705882352941

In [36]:
np.median(s)

5.0

In [37]:
from scipy import stats
stats.mode(s)

C:\Users\Amarendra Kumar\AppData\Local\Temp\ipykernel_640\3151479742.py:2: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  stats.mode(s)


ModeResult(mode=array([1]), count=array([2]))

In [38]:
s1=[1,2,3,4,5,6,7,8,9,8,7,6,5,4,3,2,1,3,4,5,6,7,852,984,324,8742,1456,985]

In [39]:
np.mean(s1)

480.32142857142856

In [40]:
np.median(s1)

6.0

In [41]:
x=2+3j

In [42]:
type(x)

complex

In [45]:
np.real(x)

2.0

In [46]:
np.imag(x)

3.0