# Numpy Array

In [1]:
import pandas as pd
import numpy as np
df1=pd.DataFrame({'id':[1,2,3,4],
                 'category':['a','s','d','f'],
                 'section':[1,'e',2,'g']})
df2=pd.DataFrame({'id':[1,2,3,4],
                 'branch':['w','e','r','t']})

In [2]:
df=pd.merge(df1,df2)
df

id category section branch
0   1        a       1      w
1   2        s       e      e
2   3        d       2      r
3   4        f       g      t

In [3]:
df['numeric']=pd.to_numeric(df['section'], errors='coerce', downcast=None)
df

id category section branch  numeric
0   1        a       1      w      1.0
1   2        s       e      e      NaN
2   3        d       2      r      2.0
3   4        f       g      t      NaN

In [4]:
df['categorical']=np.where(df['numeric'].isnull(),df['section'],np.nan)
df

id category section branch  numeric categorical
0   1        a       1      w      1.0         NaN
1   2        s       e      e      NaN           e
2   3        d       2      r      2.0         NaN
3   4        f       g      t      NaN           g

In [5]:
df.fillna(method='ffill',inplace=True)
df

id category section branch  numeric categorical
0   1        a       1      w      1.0         NaN
1   2        s       e      e      1.0           e
2   3        d       2      r      2.0           e
3   4        f       g      t      2.0           g

In [6]:
df.fillna(method='bfill',inplace=True)
df

id category section branch  numeric categorical
0   1        a       1      w      1.0           e
1   2        s       e      e      1.0           e
2   3        d       2      r      2.0           e
3   4        f       g      t      2.0           g

In [7]:
import numpy as np
type(np.array(["vbhvh", 2, 3]))

numpy.ndarray

In [8]:
#Upcasting:

In [9]:
np.array([1, 2, 3.0],dtype=int)

array([1, 2, 3])

In [10]:
#two dimensions

In [11]:
 np.array([[1, 2], [3, 4]],dtype=float)

array([[1., 2.],
       [3., 4.]])

In [12]:
#Minimum dimensions 2:

In [13]:
np.array([1, 2, 3], ndmin=4)

array([[[[1, 2, 3]]]])

In [14]:
#dtype

In [15]:
a=np.array([1, 2, 3], dtype=complex)
a

array([1.+0.j, 2.+0.j, 3.+0.j])

In [16]:
np.real(a)

array([1., 2., 3.])

In [17]:
np.imag(a)

array([0., 0., 0.])

In [18]:
#Data-type consisting of more than one element:

In [19]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [20]:
type(x[1][0])

numpy.int16

In [24]:
#Creating an array from sub-classes:

In [28]:
m1=np.mat(np.array([[1, 2],[4,7]]))
m1

matrix([[1, 2],
        [4, 7]])

In [30]:
m2=np.mat('1 2; 3 4')
m2

matrix([[1, 2],
        [3, 4]])

In [32]:
m3=m1+m2
m3

matrix([[ 2,  4],
        [ 7, 11]])

In [33]:
m1/m2

matrix([[1.        , 1.        ],
        [1.33333333, 1.75      ]])

In [34]:
m1*m2

matrix([[ 7, 10],
        [25, 36]])

In [37]:
m1

matrix([[1, 2],
        [4, 7]])

In [38]:
m1[[1],[1]]

matrix([[7]])

In [39]:
m1[[0],[1]]

matrix([[2]])

In [40]:
m1[[1],[0]]

matrix([[4]])

# numpy.asarray

In [41]:
#Convert the input to an array.

In [42]:
#Convert a list into an array:

In [43]:
 a = [1, 2]
type(a)

list

In [44]:
type(np.asarray(a))

numpy.ndarray

In [45]:
a = np.array([1,2]) #Existing arrays are not copied
type(a)

numpy.ndarray

In [46]:
np.asarray((1,2))

array([1, 2])

In [47]:
#If dtype is set, array is copied only if dtype does not match:

In [48]:
a = np.array([1,2], dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [49]:
np.asarray([1,2]) is a

False

In [50]:
b=a.copy()
b

array([1., 2.], dtype=float32)

In [51]:
np.asarray([1,2] is b)

array(False)

In [52]:
np.asarray([1,2])

array([1, 2])

In [53]:
np.asarray(a, dtype=np.float64) is a

False

In [54]:
# ndarray subclasses are not passed through

In [55]:
issubclass(np.matrix, np.ndarray)

True

In [56]:
a = np.matrix([[1, 2]])
np.asanyarray(a)

matrix([[1, 2]])

In [57]:
np.asarray(a) is a

False

In [58]:
np.asanyarray(a) is a

True

In [59]:
type(np.asarray(a))

numpy.ndarray

# numpy.asanyarray

In [60]:
a = [1, 2]
np.asanyarray(a)

array([1, 2])

In [61]:
a = np.mat([1, 2])
a

matrix([[1, 2]])

In [62]:
np.asanyarray([1,2]) is a

False

In [63]:
np.array(a, copy=True)  

array([[1, 2]])

In [64]:
#Create an array x, with a reference y and a copy z:

In [65]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [66]:
y = x

In [67]:
z = np.copy(x)

In [68]:
y[0] = 100
x

array([100,   2,   3])

In [69]:
x

array([100,   2,   3])

In [70]:
id(x[0])

2040654443536

In [71]:
id(y[0])

2040654442736

In [72]:
id(x) 

2040654439984

In [73]:
id(y)

2040654439984

# numpy.fromfunction

In [74]:
#Construct an array by executing a function over each coordinate.

In [75]:
np.fromfunction(lambda i, j: i==j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [76]:
np.fromfunction(lambda i, j: i+j, (3, 3), dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [77]:
np.fromfunction(lambda i, j: i * j, (3, 3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [78]:
#Create a new 1-dimensional array from an iterable object.

In [79]:
iterable =(x*x for x in range(5))
iterable

<generator object <genexpr> at 0x000001DB207C03C0>

In [80]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [81]:
#A new 1-D array initialized from text data in a string

In [82]:
a = np.fromstring('234 234',sep=' ')
a

array([234., 234.])

In [83]:
np.fromstring('1, 2', dtype=int, sep=',')

array([1, 2])

In [84]:
# How to create create a record array from a (flat) list of arrays

In [85]:
x1=np.array([1,2,3,4])

In [86]:
x2=np.array(['a','dd','xyz','12'])

In [87]:
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])
type(x4)

numpy.ndarray

In [88]:
r = np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('a', '<i4'), ('b', '<U3'), ('c', '<f8'), ('d', '<f8')])

In [89]:
print(r[1]["a"])

2


In [90]:
x1[1]

2

# data types

In [91]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [92]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


In [93]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")


Data type of the modified matrix: float64


Even tuples can be converted to ndarrays...


In [94]:
b = np.array([(1.5,2,3), (4,5,6)])
print("We write b = np.array([(1.5,2,3), (4,5,6)])")
print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

We write b = np.array([(1.5,2,3), (4,5,6)])
Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.  6. ]]


# arange and linspace

In [95]:
print("A series of numbers:",type(np.arange(5,16)))
np.arange(5,16,2.3)# A series of numbers from low to high

A series of numbers: <class 'numpy.ndarray'>


array([ 5. ,  7.3,  9.6, 11.9, 14.2])

In [96]:
list(np.arange(4,9,1.5))

[4.0, 5.5, 7.0, 8.5]

In [97]:
list(range(5,16,2))

[5, 7, 9, 11, 13, 15]

In [98]:
list(range(50,-1,5))

[]

In [99]:
print("Numbers spaced apart by 2:",np.arange(50,-1,5)) # Numbers spaced apart by 2

Numbers spaced apart by 2: []


In [100]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5)) # Numbers spaced apart by 2.5

Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


In [101]:
print("Every 5th number from 50 in reverse order\n",np.arange(5.0,-1,-5))

Every 5th number from 50 in reverse order
 [5. 0.]


In [102]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print((np.linspace(1,2,50)))

21 linearly spaced numbers between 1 and 5
--------------------------------------------
[1.         1.02040816 1.04081633 1.06122449 1.08163265 1.10204082
 1.12244898 1.14285714 1.16326531 1.18367347 1.20408163 1.2244898
 1.24489796 1.26530612 1.28571429 1.30612245 1.32653061 1.34693878
 1.36734694 1.3877551  1.40816327 1.42857143 1.44897959 1.46938776
 1.48979592 1.51020408 1.53061224 1.55102041 1.57142857 1.59183673
 1.6122449  1.63265306 1.65306122 1.67346939 1.69387755 1.71428571
 1.73469388 1.75510204 1.7755102  1.79591837 1.81632653 1.83673469
 1.85714286 1.87755102 1.89795918 1.91836735 1.93877551 1.95918367
 1.97959184 2.        ]


# Matrix creation

In [103]:
print("Vector of zeroes\n---------------------")
print(np.zeros(5))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]


In [104]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [105]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4))) #Notice Tuples

Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [106]:
print("Vector of ones\n---------------------")
print(np.ones(5))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]


In [107]:
print("Matrix of ones\n---------------------")
print(np.ones((5,2,8),dtype=int)) #Note matrix dimension specified by Tuples


Matrix of ones
---------------------
[[[1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]]]


In [108]:
print("Matrix of 5's\n---------------------")
print(5+np.ones((3,5)))

Matrix of 5's
---------------------
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [109]:
print("Empty matrix\n-------------\n", np.empty((3,5)))

Empty matrix
-------------
 [[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [110]:
mat1 = np.eye(4) 
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [111]:
np.arange(3,5,0.25)

array([3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75])

In [112]:
np.arange(3.0)

array([0., 1., 2.])

In [113]:
 np.arange(3,7)

array([3, 4, 5, 6])

In [114]:
np.arange(3,7,2)

array([3, 5])

In [115]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [116]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [117]:
np.linspace(2.0, 3.0, num=9, retstep=True)

(array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ]), 0.125)

In [118]:
#Return numbers spaced evenly on a log scale.
np.linspace(2.0, 3.0, num=4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [119]:
np.logspace(2.0, 3.0, num=4,base = 10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [120]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

array([100.        , 177.827941  , 316.22776602, 562.34132519])

In [121]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

In [122]:
#Extract a diagonal or construct a diagonal array.

In [123]:
x = np.arange(16).reshape((-1,4))

In [124]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [125]:
np.diag(x)

array([ 0,  5, 10, 15])

In [126]:
np.diag(x, k=2)

array([2, 7])

In [127]:
np.diag(x, k=-1)

array([ 4,  9, 14])

In [128]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [129]:
#Create a two-dimensional array with the flattened input as a diagonal.

In [130]:
np.diagflat([[1,2],[3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [131]:
np.diagflat([1,2], 1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [132]:
#An array with ones at and below the given diagonal and zeros elsewhere.

In [133]:
np.tri(3, 5, 1, dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [134]:
np.tri(3, 5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [135]:
#return a Lower triangle of an array.

In [136]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [137]:
#return Upper triangle of an array.

In [138]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

# Random number generation

In [139]:
print("Random number generation (from Uniform distribution)")
print(np.round(np.random.rand(2,3))) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

Random number generation (from Uniform distribution)
[[0. 1. 1.]
 [0. 0. 1.]]


In [140]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[ 0.6502349  -0.22926038  0.87817735]
 [ 0.81675818 -0.31281319  0.86390331]
 [-1.16388287 -0.19760902  0.52153552]
 [ 1.6684935  -0.83076079  0.56221023]]


In [141]:
print("Random integer vector:",np.random.randint(1,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")


Random integer vector: 2

Random integer matrix


In [142]:
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

[[21 46 11 13]
 [30 48 33 15]
 [76 33 27 57]
 [ 7 63 88 55]]

20 samples drawn from a dice throw: [5 1 3 6 1 5 5 4 2 4 5 3 3 1 6 6 1 2 4 4]


# Reshaping

In [143]:
from numpy.random import randint as rn
a = rn(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,-19878)
c

array([[70, 30, 58, 96, 11],
       [15, 87, 68,  1, 11],
       [14, 43, 30, 63, 56],
       [72, 47, 71, 21,  8],
       [46, 37, 38, 21, 31],
       [70, 67, 16, 27,  3]])

In [144]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)


Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [145]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)



a looks like
 -------------------- 
 [70 30 58 96 11 15 87 68  1 11 14 43 30 63 56 72 47 71 21  8 46 37 38 21
 31 70 67 16 27  3] 
 --------------------

b looks like
 -------------------- 
 [[[70 30 58 96 11]
  [15 87 68  1 11]
  [14 43 30 63 56]]

 [[72 47 71 21  8]
  [46 37 38 21 31]
  [70 67 16 27  3]]] 
 --------------------

c looks like
 -------------------- 
 [[70 30 58 96 11]
 [15 87 68  1 11]
 [14 43 30 63 56]
 [72 47 71 21  8]
 [46 37 38 21 31]
 [70 67 16 27  3]] 
 --------------------


In [146]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))


NameError: name 'ri' is not defined

In [ ]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
#print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=1, kind='mergesort'))
M

In [ ]:
print("Max of a:", M.max())
print("Max of b:", b.max())
b

In [147]:
M

NameError: name 'M' is not defined

In [148]:
print("Max of a location:", M.argmax(axis= 1 ))
print("Max of b location:", b.argmax())
print("Max of c location:", b.argmax())

NameError: name 'M' is not defined

# Indexing and slicing

In [149]:
arr = np.arange(0,11)
print("Array:",arr)


Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [150]:
print("Element at 7th index is:", arr[7])


Element at 7th index is: 7


In [151]:
print("Elements from 3rd to 5th index are:", arr[3:6:2])


Elements from 3rd to 5th index are: [3 5]


In [152]:
print("Elements up to 4th index are:", arr[:4])
arr

Elements up to 4th index are: [0 1 2 3]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [153]:
print("Elements from last backwards are:", arr[-1:7:-1])


Elements from last backwards are: [10  9  8]


In [154]:
print("3 Elements from last backwards are:", arr[-1:-6:2])


3 Elements from last backwards are: []


In [155]:
arr = np.arange(0,21,2)
print("New array:",arr)

New array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [156]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [157]:
import numpy as np 
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat[1:4,3:5]
mat[0:3,[1,3]]

NameError: name 'ri' is not defined

In [158]:
mat[0:3,[1,3]]
mat

IndexError: index 3 is out of bounds for axis 1 with size 3

In [159]:
print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[1][1])
mat


Double bracket indexing
------------------------
Element in row index 1 and column index 2: 5.2


array([[1.1, 2. , 3. ],
       [4. , 5.2, 6. ],
       [7. , 8.3, 9. ]])

In [160]:
print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n----------------------")



Single bracket with comma indexing
----------------------------------
Element in row index 1 and column index 2: 6.0

Row or column extract
----------------------


In [161]:
print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])


Entire row at index 2: [7.  8.3 9. ]


IndexError: index 3 is out of bounds for axis 1 with size 3

In [162]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])



Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 []


In [163]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

IndexError: index 3 is out of bounds for axis 1 with size 3

# Subseting

In [164]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat>50

NameError: name 'ri' is not defined

In [165]:
print ("Elements greater than 50\n", mat[mat>50])

Elements greater than 50
 []


# Slicing

In [166]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [167]:
mat_slice = mat[:2,:2]
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")


Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix


In [168]:
mat_slice[0,0] = 1000
print (mat_slice)

[[1000   12]
 [  21   22]]


In [169]:
print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)



But the original matrix? WHOA! It got changed too!
[[1000   12   13]
 [  21   22   23]
 [  31   32   33]]


In [170]:
# Little different way to create a copy of the slixed matrix
print ("\nDoing it again little differently now...\n")
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)



Doing it again little differently now...

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [171]:
mat_slice = np.array(mat[:2,:2]) # Notice the np.array command to create a new array not just slicing
print ("\nSliced matrix")
print(mat_slice)



Sliced matrix
[[11 12]
 [21 22]]


In [172]:
print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)



Change the sliced matrix
[[1000   12]
 [  21   22]]


In [173]:
print("\nBut the original matrix? NO CHANGE this time:)")
print(mat)


But the original matrix? NO CHANGE this time:)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


# Universal Functions

In [174]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


NameError: name 'ri' is not defined

In [175]:
mat1*mat2

NameError: name 'mat2' is not defined

In [176]:
#print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1@mat2)


NameError: name 'mat2' is not defined

In [177]:
print("\nDivision\n------------------\n", mat1/0)
#print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)



Division
------------------
 [[inf nan nan nan]
 [nan inf nan nan]
 [nan nan inf nan]
 [nan nan nan inf]]


C:\Users\Amarendra Kumar\AppData\Local\Temp\ipykernel_13508\2948643470.py:1: RuntimeWarning: divide by zero encountered in divide
  print("\nDivision\n------------------\n", mat1/0)
C:\Users\Amarendra Kumar\AppData\Local\Temp\ipykernel_13508\2948643470.py:1: RuntimeWarning: invalid value encountered in divide
  print("\nDivision\n------------------\n", mat1/0)


In [178]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)



Addition of a scalar (100)
-------------------------
 [[101. 100. 100. 100.]
 [100. 101. 100. 100.]
 [100. 100. 101. 100.]
 [100. 100. 100. 101.]]


In [179]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,3))


Exponentiation, matrix cubed here
----------------------------------------
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Broadcasting

In [180]:
#NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
#In the simplest case, the two arrays must have exactly the same shape.
#NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
#When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
#dimensions, and works its way forward. Two dimensions are compatible when
#they are equal, or one of them is 1

In [181]:
start = np.zeros((4,4))
start= start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [182]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2,5])
print(add_rows)

[1 0 2 5]


In [178]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [155]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [156]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [157]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+y)

[[200. 200. 200. 200.]
 [201. 201. 201. 201.]
 [202. 202. 202. 202.]
 [203. 203. 203. 203.]]


# Array Math

In [158]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)


NameError: name 'ri' is not defined

In [159]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))



Sq-root of 1st matrix using np
------------------
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [160]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))



Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[2.71828183 1.         1.         1.        ]
 [1.         2.71828183 1.         1.        ]
 [1.         1.         2.71828183 1.        ]
 [1.         1.         1.         2.71828183]]


In [161]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))
print(mat1)
print(mat2)


10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[  0. -inf -inf -inf]
 [-inf   0. -inf -inf]
 [-inf -inf   0. -inf]
 [-inf -inf -inf   0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


C:\Users\Amarendra Kumar\AppData\Local\Temp\ipykernel_10960\4159835803.py:1: RuntimeWarning: divide by zero encountered in log10
  print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))


NameError: name 'mat2' is not defined

In [162]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))
mat1%mat2

NameError: name 'mat2' is not defined

In [163]:
print("\nCombination of functions by shwoing exponetial decay of a sine wave\n",'-'*70)



Combination of functions by shwoing exponetial decay of a sine wave
 ----------------------------------------------------------------------


In [164]:
A = np.linspace(0,12*np.pi,1001)


In [165]:
A

array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])

In [166]:
import numpy as np

In [167]:
np.mat(np.array([[1,2],[3,4]]))

matrix([[1, 2],
        [3, 4]])